name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Wait for CI to finish

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: my-node-app  # Name from AWS
        environment_name: MyNodeApp-env  # Check your AWS Elastic Beanstalk dashboard
        region: us-east-1  # Change if your AWS is in another region
        version_label: v1
